#ifndef PARTICLESYSTEM_H
#define PARTICLESYSTEM_H

#include "Buffer.h"
#include "Shaders.h"
#include "ResourceHandler.h"
#include "Camera.h"

class ParticleSystem
{
private:
    // Device
    ID3D11Device* m_device;
    ID3D11DeviceContext* m_deviceContext;

    bool m_disposed;

    // Maximum number of particles that can be created
    int m_maxParticles;

    // on the first run, we need to use a different vertex buffer to initialize the system
    bool m_firstRun;

    // Switching Buffers Bool
    bool m_drawing;

    // How long the system has existed
    float m_age;

    // Constant Buffer
    GS_PARTICLE_CBUFFER particleData;
    Buffer<GS_PARTICLE_CBUFFER> particleCBuffer;

    // Shaders
    Shaders m_drawShaders;
    Shaders m_streamOutputShaders;

    // Vertex Buffers
    // A vertex buffer containing the original emitter particles
    Buffer<VertexParticle> m_initVertexBuffer;
    // vertex buffer to hold the particles to be drawn
    Buffer<VertexParticle> m_drawVertexBuffer;
    // vertex buffer to receive the particles generated by the stream-out shader
    Buffer<VertexParticle> m_streamOutVertexBuffer;

    // Textures
    // a texture array to contain the sprites to be applied to the drawn particles
    ID3D11ShaderResourceView* m_texArraySRV;
    // a texture containing random floats, used to supply the shader with random values 
    ID3D11ShaderResourceView* m_randomTexSRV;

public:
    ParticleSystem();

    // Initialization
    void Initialize(ID3D11Device* device, ID3D11DeviceContext* deviceContext, std::wstring texArrayPath, int maxParticles);

    // Getters
    float getAge() const { return m_age; }

    // Setters
    void setAge(float newAge) { m_age = newAge; }

    // Update
    void reset();
    void update(float dt, float gameTime, Camera &camera);

    // Render
    void render();
};

#endif // !PARTICLESYSTEM_H